itle: 東京アートまとめ
email: yourname@example.com
url: "https://stadahiro.github.io"  # 独自ドメインを取得したら置換
remote_theme: "mmistakes/minimal-mistakes"
logo: "/assets/images/logo.svg"      # 任意
paginate: 10
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
# ナビゲーション設定（Minimal Mistakes 用）
header_pages:
  - about.md
  - museums.md
  - tags/index.html
atom_feed:
  hide: false