name: Import exhibitions
on:
  schedule:
    - cron:  '0 1 * * *'   # JST 10:00 毎日
  workflow_dispatch:        # 手動実行ボタン
jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install deps
        run: pip install feedparser markdownify python-slugify
      - uses: EndBug/add-and-commit@v9
        with:
          add: "_posts/*.md"
          message: "auto: import exhibitions"
      - name: Scrape MOMAT
        run: python scripts/scrape_momat.py