ame: Scrape exhibitions

on:
  schedule:
    - cron:  '0 1 * * *'   # JST 10:00 毎日
  workflow_dispatch:        # 手動実行

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests beautifulsoup4 python-slugify

      # 国立西洋美術館
      - name: Scrape NMWA (国立西洋美術館)
        run: python scripts/scrape_nmwa.py

      # ここに他館のスクリプトを追加していく
      # - name: Scrape MOMAT
      #   run: python scripts/scrape_momat.py

      - uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: "_posts/*.md"
          pathspec_error_handling: ignore   # ファイルが無くてもエラーにしない
          default_author: github_actions
          message: "auto: import exhibitions (scraping)"